FROM openjdk:17
EXPOSE 8080
ADD target/DocumentDb-SpringReadNodes-0.0.1-SNAPSHOT.jar DocumentDb-SpringReadNodes-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/DocumentDb-SpringReadNodes-0.0.1-SNAPSHOT.jar"]


#FROM tomcat:9.0-jre17-alpine

#FROM tomcat:9.0-jdk17
#COPY target/DocumentDb-SpringReadNodes-0.0.1-SNAPSHOT.jar $CATALINA_HOME/webapps/DocumentDb-SpringReadNodes-0.0.1-SNAPSHOT.jar